[tool.poetry]
name = "arrnounced"
version = "0.7.0"
description = "Notify Sonarr/Radarr/Lidarr of tracker IRC announcements"
authors = ["WeAnnounce <weannounce@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
